// app/layout.js
import { Asap_Condensed } from "next/font/google";
import "./globals.css";

const asap = Asap_Condensed({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600"],
  variable: "--font-asap-condensed",
});

export const metadata = {
  title: "Nutritional Insights",
  description: "Generated by create next app",
  icons: {
    icon: "/diet-food.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${asap.variable} font-sans`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
